# Generated by Django 3.1.3 on 2020-12-13 15:12

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_game', models.CharField(default=main.models.get_code, max_length=6)),
                ('user1', models.CharField(max_length=100, null=True)),
                ('uesr2', models.CharField(max_length=100, null=True)),
                ('game_stats', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
