# Generated by Django 3.1.3 on 2020-12-13 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='uesr2',
            new_name='user2',
        ),
    ]
